version: '3.8'

services:
  prefect-server:
    build: .
    restart: unless-stopped
    environment:
      - PREFECT_API_KEY=${PREFECT_API_KEY}
      - PREFECT_BASIC_AUTH=${PREFECT_BASIC_AUTH}
      - PREFECT_API_URL=${PREFECT_API_URL}
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_SERVER_API_PORT=4200
    ports:
      - "4200:4200"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4200/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
